apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-devops-frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-devops-frontend
  template:
    metadata:
      labels:
        app: my-devops-frontend
    spec:
      containers:
        - name: my-devops-frontend
          image: <your-docker-image> # Replace with your Docker image path
          ports:
            - containerPort: 3000
