name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Docker Build and Push
        run: |
          docker build -t my-devops-frontend:latest .
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker tag my-devops-frontend:latest ${{ secrets.DOCKER_USERNAME }}/my-devops-frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-devops-frontend:latest

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/my-devops-frontend my-devops-frontend=${{ secrets.DOCKER_USERNAME }}/my-devops-frontend:latest
